# Generated by Django 2.0.1 on 2018-01-15 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('fecha_de_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
